version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/proyecto_db
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: contraseña

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm start
    depends_on:
      - backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: proyecto_db
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
